[package]
name = "sun-sensor"
version = "0.1.0"
edition = "2024"

[dependencies]
nexosim = { git = "https://github.com/asynchronics/nexosim.git", rev="9c16ca8" }
serde = "1.0.228"
rand_distr = "0.4.3"
rand = { version = "0.8.5", features = ["small_rng"] }